### ISSUE TITLE
Export bakedsdf with textures 

### ISSUE THREAD

**Issue by antithing** [autonomousvision/sdfstudio#105]
Hi, and thank you for sharing this code. 
I am looking at the mesh extract for bakedsdf, and it looks like a ply file. 

Is it possible to extract a textured mesh? 

If not, this would be a great addition. 

Obj is a straightforward format, usually used with jpg or png holding the texture data. 

Thanks!

**Comment by niujinshuchong** [comment]
Hi, extracting textured mesh is not supported for sdf-based methods. But It should be easy to add this functionality since nerfstudio already implemented it. You can call this function https://github.com/autonomousvision/sdfstudio/blob/master/scripts/exporter.py#L162-L169 after you extract the mesh with `ns-extract-mesh` here: https://github.com/autonomousvision/sdfstudio/blob/master/scripts/extract_mesh.py#L105

**Comment by antithing** [comment]
Thank you! Understood.
