### ISSUE TITLE
Has BakedSDF been acclerated?

### ISSUE THREAD

**Issue by CCamouflage-Hvv** [autonomousvision/sdfstudio#89]
Hi, thanks for you work sincerely! @autonomousvision
I can see your annotation in [method_configs.py](https://github.com/autonomousvision/sdfstudio/blob/a10a5d71de24ad2cc5c01456302f3d4feb74e050/nerfstudio/configs/method_configs.py) of bakedsdf, which said '"bakedsdf": "Implementation of BakedSDF with multi-res hash grids".'. 
What I want to consult is if the multi-res hash grids has acclerated the BakedSDF training procedure? (I still have to spend over 20 hours in a training procedure with 25k iterations. )

**Comment by niujinshuchong** [comment]
@CCamouflage-Hvv Using hash encoding will speed up the training compared with using a big MLP because each iteration is several times faster. But I also set a large batch size for the hash grids here: https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/configs/method_configs.py#L117. I can train the model in ~7 hours with the default setting (250K iterations and 8192 batch size) in an A100.

**Comment by CCamouflage-Hvv** [comment]
Thanks a lot!!!
